### ISSUE TITLE
Define classes and algrithm for effective operation of the relase notes generation

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/generate-release-notes#103]
## Background
The current data structures and the steps data are extracted from GitHub API might be not the most suitable for all the features requested.
Brainstorm and design the best data structures and steps of the program to fill them and utilize them.

## Desired Outcome
1. Best data structures
2. Algorithmic steps for processing

```[tasklist]
### Tasks
- [ ] Design data structures
- [ ] Algorithm to fill them
- [ ] Models of the usage
```

**Comment by miroslavpojer** [comment]
Suggestion:

Ahoj, vcera prisel David s myslenkou jine datove struktury a posleze prezentace v ramci RLS notes vystupu.

Jde o to, ze muze exitovat nekolik moznosti vztahu Issues <==> PRs <==> Commits



Issue, PR, Commit
0, 0, 1 - Direct commit
1, 0, 0 - Issue without PR
1, 1, 1 
0, 1, 1 - PR without Issue with 1 Commit
0, 1, Z - PR without Issue with Z Commit

1, Y, Z - dnes design - radek je primarne vztah 1 Issue Y PRs a Z Commits
X, Y, Z - weak point of today's design

co kdyz je vice Issue odkazanych z jednoho PR - neresim typ vazby, Fixed, Solved, Mention


Legenda - pismena, jsou ruzne pocty



David prisel s tim, ze by bylo mozne definovat class Line - reprezentujici jeden radek libovolne kapitoly

kde Line muze obsahovat:

X Issues (Class Issue)
Y PRs (Class PullRequest)
Z Commits (Class Commit)

Problemy, ktere v tom vidim - obecne:

style prace #1

mam 1 Issue a 1 .. N PRs ktera prinaseji zmenu => serie mensich uprav
je kazde PR nositelem RLS notes a musi byt?
styl prace #2

mam 1 PR, ktere prinasi zmenu a ma na sobe RLS notes
PR muze odkazovat na vice Issues

Myslenky k debate:

umoznit zvolit si uhel pohledu pri generovani vystupu  => jina prace s instancemi Line

Issue oriented - to mame nyni (data: one Issue per line instance)
PR oriented - tohle je tusim Davidovo videni (data: one PR per line instance)
line jako summary vsech vazeb

X Issues, Y PRs, Z Commits
kde pro line muze byt serie podporovanych placeholders

az logika by rozhodla, kde dokaze z dostupnych dat vratit data

**Comment by benedeki** [comment]
## My suggestions:
The central class in `ReleaseNotesEntry`.

### Github Item classes
`class SourceObject(var inARNEnty: Boolean)`
`class GitHubItem(number: Integer, ..) extends SourceObject`
`class Issue extends GitHubItem`
`class PullRequest extends GitHubItem`
`class Commit(commitMessage: String, ....)extends SourceObject

### Release notes
```python
class ReleaseNotesEntry(
  entry: String,
  issues: List[Issue],
  pullRequests: List[PullRequest]
  commits: List[Commit]
)
```
can be created either from Issue or PR.

### Algorithm
* create an MxN map of issues and PR, how they are connectd
* link commits to PRs
* release notes in Issue:
  *  go through issues, create `ReleaseNotesEntry` based on them
* release notes in PR:
  *  go through PR, create `ReleaseNotesEntry` based on them
* take remaining issues, PR and commits to generate "special `ReleaseNotesEntry`

**Comment by miroslavpojer** [comment]
**New User control:** Define where Release notes are defined: `Issue`, `PR`
- Note: for now release notes will be placed in body of Issue or PR

**Class structure:**
- class ReleaseNotesEntry
  - entries can be empty list ==>  mean no RLS notes defined
```
class ReleaseNotesEntry(
  entries: List[String],
  issues: List[Issue],
  pullRequests: List[PullRequest]
  commits: List[Commit]
)
```
- `class SourceObject(var inARNEnty: Boolean)`
  - hold users decision about source of RLS notes 
- `class GitHubItem(number: Integer, ..) extends SourceObject`
  - ancestor for Issue and PR holding shared attributes and logic 
- `class Issue extends GitHubItem` 
- `class PullRequest extends GitHubItem`
- `class Commit(commitMessage: String, ....)extends SourceObject`

**Algorithm**
- **data mining**
  - get all Issue from latest RLS (in all states!) - 1 API call
  - get all PRs from latest RLS - 1 API call
  - get all PRs related commits - 1 API call per PR
  - get all commits from latest RLS - 1 API call
- **data linking**
  - create a MxN bilateral graph of issues and PR
    - Note: connect Issues to PRs or PRs to Issues
  - filter out direct commits
- **ReleaseNotesEntry instance creation**
  - if release notes in Issue (M == 1):
    - go through issues, create ReleaseNotesEntry based on them
  - if release notes in PR (N == 1):
    - go through PR, create ReleaseNotesEntry based on them
  -  take remaining issues, PR and commits to generating "special ReleaseNotesEntry" types
- **RLS notes generation**
  - chapters
    - their control is not part of this spike 
  - chapter rows
    - types: Issue, PR, direct commit
    - each type has its own default format of row, user can define customized format
      - `Issue: {number} _{title}_ {pull-requests} ... \n{rls-notes}`
      - `PR: {number} _{title}_ {pull-requests} ... \n{rls-notes}`
      - `Commit: {sha} _{author}_ {contributors}\n{message}`

**Summary**
- No special label is needed for the generator.
- Special label(s) will be used only for GH check workflow (check the presence of Release notes)

**Comment by miroslavpojer** [comment]
The Outcomes have been reached. Closing this epic, but it will be noted as a possible source of information about placeholder logic.
