### ISSUE TITLE
Refactoring from Javascript to python custom action

### ISSUE THREAD

**Issue by miroslavpojer** [AbsaOSS/generate-release-notes#46]
**Goal**
Release a new version of the Release Notes generator.

**Target changes and features**
- Changes:
  - Migration to GH composite type of action. (building more similar actions and solving API call rate limits)
  - Improve efficiency in the count of API Calls to reach the limit as late as possible. (lazy data loading based on user configuration)

```[tasklist]
### Tasks
- [ ] https://github.com/AbsaOSS/generate-release-notes/issues/43
- [x] https://github.com/AbsaOSS/generate-release-notes/issues/48
- [ ] https://github.com/AbsaOSS/generate-release-notes/issues/50
```

**Comment by miroslavpojer** [comment]
Epic solved.
